/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSaleProjectsRouteImport } from './routes/_app.sale-projects'
import { Route as AppSaleLandingsRouteImport } from './routes/_app.sale-landings'
import { Route as AppSaleCustomersRouteImport } from './routes/_app.sale-customers'
import { Route as AppQrSharingRouteImport } from './routes/_app.qr-sharing'
import { Route as AppPromptLibraryRouteImport } from './routes/_app.prompt-library'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppNfcCodesRouteImport } from './routes/_app.nfc-codes'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppMarketingRouteImport } from './routes/_app.marketing'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppLeadCaptureRouteImport } from './routes/_app.lead-capture'
import { Route as AppLandingsRouteImport } from './routes/_app.landings'
import { Route as AppFilesRouteImport } from './routes/_app.files'
import { Route as AppDynamicQrRouteImport } from './routes/_app.dynamic-qr'
import { Route as AppDigitalCardRouteImport } from './routes/_app.digital-card'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContentLibraryRouteImport } from './routes/_app.content-library'
import { Route as AppCardDesignerRouteImport } from './routes/_app.card-designer'
import { Route as AppAuthSettingsRouteImport } from './routes/_app.auth-settings'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAirdropRouteImport } from './routes/_app.airdrop'
import { Route as AppAiSalesPageRouteImport } from './routes/_app.ai-sales-page'
import { Route as AppAiLeadScoreRouteImport } from './routes/_app.ai-lead-score'
import { Route as AppAiFollowupRouteImport } from './routes/_app.ai-followup'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'
import { Route as AppAiFollowupCustomerIdRouteImport } from './routes/_app.ai-followup.$customerId'
import { Route as ApiPublicTCodeRouteImport } from './routes/api/public/t.$code'
import { Route as ApiPublicSalesPagesSlugRouteImport } from './routes/api/public/sales-pages.$slug'
import { Route as ApiPublicQCodeRouteImport } from './routes/api/public/q.$code'
import { Route as ApiPublicPqCodeRouteImport } from './routes/api/public/pq.$code'
import { Route as ApiPublicLeadFormsSlugRouteImport } from './routes/api/public/lead-forms.$slug'
import { Route as ApiPublicLandingManifestSlugRouteImport } from './routes/api/public/landing-manifest.$slug'
import { Route as ApiPublicCardLeadsSlugRouteImport } from './routes/api/public/card-leads.$slug'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSaleProjectsRoute = AppSaleProjectsRouteImport.update({
  id: '/sale-projects',
  path: '/sale-projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSaleLandingsRoute = AppSaleLandingsRouteImport.update({
  id: '/sale-landings',
  path: '/sale-landings',
  getParentRoute: () => AppRoute,
} as any)
const AppSaleCustomersRoute = AppSaleCustomersRouteImport.update({
  id: '/sale-customers',
  path: '/sale-customers',
  getParentRoute: () => AppRoute,
} as any)
const AppQrSharingRoute = AppQrSharingRouteImport.update({
  id: '/qr-sharing',
  path: '/qr-sharing',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptLibraryRoute = AppPromptLibraryRouteImport.update({
  id: '/prompt-library',
  path: '/prompt-library',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppNfcCodesRoute = AppNfcCodesRouteImport.update({
  id: '/nfc-codes',
  path: '/nfc-codes',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadCaptureRoute = AppLeadCaptureRouteImport.update({
  id: '/lead-capture',
  path: '/lead-capture',
  getParentRoute: () => AppRoute,
} as any)
const AppLandingsRoute = AppLandingsRouteImport.update({
  id: '/landings',
  path: '/landings',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppDynamicQrRoute = AppDynamicQrRouteImport.update({
  id: '/dynamic-qr',
  path: '/dynamic-qr',
  getParentRoute: () => AppRoute,
} as any)
const AppDigitalCardRoute = AppDigitalCardRouteImport.update({
  id: '/digital-card',
  path: '/digital-card',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContentLibraryRoute = AppContentLibraryRouteImport.update({
  id: '/content-library',
  path: '/content-library',
  getParentRoute: () => AppRoute,
} as any)
const AppCardDesignerRoute = AppCardDesignerRouteImport.update({
  id: '/card-designer',
  path: '/card-designer',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthSettingsRoute = AppAuthSettingsRouteImport.update({
  id: '/auth-settings',
  path: '/auth-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAirdropRoute = AppAirdropRouteImport.update({
  id: '/airdrop',
  path: '/airdrop',
  getParentRoute: () => AppRoute,
} as any)
const AppAiSalesPageRoute = AppAiSalesPageRouteImport.update({
  id: '/ai-sales-page',
  path: '/ai-sales-page',
  getParentRoute: () => AppRoute,
} as any)
const AppAiLeadScoreRoute = AppAiLeadScoreRouteImport.update({
  id: '/ai-lead-score',
  path: '/ai-lead-score',
  getParentRoute: () => AppRoute,
} as any)
const AppAiFollowupRoute = AppAiFollowupRouteImport.update({
  id: '/ai-followup',
  path: '/ai-followup',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAiFollowupCustomerIdRoute = AppAiFollowupCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppAiFollowupRoute,
} as any)
const ApiPublicTCodeRoute = ApiPublicTCodeRouteImport.update({
  id: '/api/public/t/$code',
  path: '/api/public/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSalesPagesSlugRoute = ApiPublicSalesPagesSlugRouteImport.update({
  id: '/api/public/sales-pages/$slug',
  path: '/api/public/sales-pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQCodeRoute = ApiPublicQCodeRouteImport.update({
  id: '/api/public/q/$code',
  path: '/api/public/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPqCodeRoute = ApiPublicPqCodeRouteImport.update({
  id: '/api/public/pq/$code',
  path: '/api/public/pq/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadFormsSlugRoute = ApiPublicLeadFormsSlugRouteImport.update({
  id: '/api/public/lead-forms/$slug',
  path: '/api/public/lead-forms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLandingManifestSlugRoute =
  ApiPublicLandingManifestSlugRouteImport.update({
    id: '/api/public/landing-manifest/$slug',
    path: '/api/public/landing-manifest/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCardLeadsSlugRoute = ApiPublicCardLeadsSlugRouteImport.update({
  id: '/api/public/card-leads/$slug',
  path: '/api/public/card-leads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customize': typeof CustomizeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/thank-you': typeof ThankYouRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ai-followup': typeof AppAiFollowupRouteWithChildren
  '/ai-lead-score': typeof AppAiLeadScoreRoute
  '/ai-sales-page': typeof AppAiSalesPageRoute
  '/airdrop': typeof AppAirdropRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/auth-settings': typeof AppAuthSettingsRoute
  '/card-designer': typeof AppCardDesignerRoute
  '/content-library': typeof AppContentLibraryRoute
  '/dashboard': typeof AppDashboardRoute
  '/digital-card': typeof AppDigitalCardRoute
  '/dynamic-qr': typeof AppDynamicQrRoute
  '/files': typeof AppFilesRoute
  '/landings': typeof AppLandingsRoute
  '/lead-capture': typeof AppLeadCaptureRoute
  '/leads': typeof AppLeadsRoute
  '/marketing': typeof AppMarketingRoute
  '/members': typeof AppMembersRoute
  '/nfc-codes': typeof AppNfcCodesRoute
  '/pipeline': typeof AppPipelineRoute
  '/products': typeof AppProductsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/prompt-library': typeof AppPromptLibraryRoute
  '/qr-sharing': typeof AppQrSharingRoute
  '/sale-customers': typeof AppSaleCustomersRoute
  '/sale-landings': typeof AppSaleLandingsRoute
  '/sale-projects': typeof AppSaleProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/timeline': typeof AppTimelineRoute
  '/wallet': typeof AppWalletRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/c/$slug': typeof CSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/share/$slug': typeof ShareSlugRoute
  '/ai-followup/$customerId': typeof AppAiFollowupCustomerIdRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/api/public/card-leads/$slug': typeof ApiPublicCardLeadsSlugRoute
  '/api/public/landing-manifest/$slug': typeof ApiPublicLandingManifestSlugRoute
  '/api/public/lead-forms/$slug': typeof ApiPublicLeadFormsSlugRoute
  '/api/public/pq/$code': typeof ApiPublicPqCodeRoute
  '/api/public/q/$code': typeof ApiPublicQCodeRoute
  '/api/public/sales-pages/$slug': typeof ApiPublicSalesPagesSlugRoute
  '/api/public/t/$code': typeof ApiPublicTCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customize': typeof CustomizeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/thank-you': typeof ThankYouRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ai-followup': typeof AppAiFollowupRouteWithChildren
  '/ai-lead-score': typeof AppAiLeadScoreRoute
  '/ai-sales-page': typeof AppAiSalesPageRoute
  '/airdrop': typeof AppAirdropRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/auth-settings': typeof AppAuthSettingsRoute
  '/card-designer': typeof AppCardDesignerRoute
  '/content-library': typeof AppContentLibraryRoute
  '/dashboard': typeof AppDashboardRoute
  '/digital-card': typeof AppDigitalCardRoute
  '/dynamic-qr': typeof AppDynamicQrRoute
  '/files': typeof AppFilesRoute
  '/landings': typeof AppLandingsRoute
  '/lead-capture': typeof AppLeadCaptureRoute
  '/leads': typeof AppLeadsRoute
  '/marketing': typeof AppMarketingRoute
  '/members': typeof AppMembersRoute
  '/nfc-codes': typeof AppNfcCodesRoute
  '/pipeline': typeof AppPipelineRoute
  '/products': typeof AppProductsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/prompt-library': typeof AppPromptLibraryRoute
  '/qr-sharing': typeof AppQrSharingRoute
  '/sale-customers': typeof AppSaleCustomersRoute
  '/sale-landings': typeof AppSaleLandingsRoute
  '/sale-projects': typeof AppSaleProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/timeline': typeof AppTimelineRoute
  '/wallet': typeof AppWalletRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/c/$slug': typeof CSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/share/$slug': typeof ShareSlugRoute
  '/ai-followup/$customerId': typeof AppAiFollowupCustomerIdRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/customers': typeof AppCustomersIndexRoute
  '/api/public/card-leads/$slug': typeof ApiPublicCardLeadsSlugRoute
  '/api/public/landing-manifest/$slug': typeof ApiPublicLandingManifestSlugRoute
  '/api/public/lead-forms/$slug': typeof ApiPublicLeadFormsSlugRoute
  '/api/public/pq/$code': typeof ApiPublicPqCodeRoute
  '/api/public/q/$code': typeof ApiPublicQCodeRoute
  '/api/public/sales-pages/$slug': typeof ApiPublicSalesPagesSlugRoute
  '/api/public/t/$code': typeof ApiPublicTCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/thank-you': typeof ThankYouRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/ai-followup': typeof AppAiFollowupRouteWithChildren
  '/_app/ai-lead-score': typeof AppAiLeadScoreRoute
  '/_app/ai-sales-page': typeof AppAiSalesPageRoute
  '/_app/airdrop': typeof AppAirdropRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/auth-settings': typeof AppAuthSettingsRoute
  '/_app/card-designer': typeof AppCardDesignerRoute
  '/_app/content-library': typeof AppContentLibraryRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/digital-card': typeof AppDigitalCardRoute
  '/_app/dynamic-qr': typeof AppDynamicQrRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/landings': typeof AppLandingsRoute
  '/_app/lead-capture': typeof AppLeadCaptureRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/nfc-codes': typeof AppNfcCodesRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/prompt-library': typeof AppPromptLibraryRoute
  '/_app/qr-sharing': typeof AppQrSharingRoute
  '/_app/sale-customers': typeof AppSaleCustomersRoute
  '/_app/sale-landings': typeof AppSaleLandingsRoute
  '/_app/sale-projects': typeof AppSaleProjectsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/wallet': typeof AppWalletRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/c/$slug': typeof CSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/share/$slug': typeof ShareSlugRoute
  '/_app/ai-followup/$customerId': typeof AppAiFollowupCustomerIdRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/api/public/card-leads/$slug': typeof ApiPublicCardLeadsSlugRoute
  '/api/public/landing-manifest/$slug': typeof ApiPublicLandingManifestSlugRoute
  '/api/public/lead-forms/$slug': typeof ApiPublicLeadFormsSlugRoute
  '/api/public/pq/$code': typeof ApiPublicPqCodeRoute
  '/api/public/q/$code': typeof ApiPublicQCodeRoute
  '/api/public/sales-pages/$slug': typeof ApiPublicSalesPagesSlugRoute
  '/api/public/t/$code': typeof ApiPublicTCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customize'
    | '/login'
    | '/onboarding'
    | '/thank-you'
    | '/verify-email'
    | '/ai-followup'
    | '/ai-lead-score'
    | '/ai-sales-page'
    | '/airdrop'
    | '/analytics'
    | '/appointments'
    | '/auth-settings'
    | '/card-designer'
    | '/content-library'
    | '/dashboard'
    | '/digital-card'
    | '/dynamic-qr'
    | '/files'
    | '/landings'
    | '/lead-capture'
    | '/leads'
    | '/marketing'
    | '/members'
    | '/nfc-codes'
    | '/pipeline'
    | '/products'
    | '/projects'
    | '/prompt-library'
    | '/qr-sharing'
    | '/sale-customers'
    | '/sale-landings'
    | '/sale-projects'
    | '/settings'
    | '/team'
    | '/timeline'
    | '/wallet'
    | '/accept-invite/$token'
    | '/c/$slug'
    | '/f/$slug'
    | '/p/$slug'
    | '/share/$slug'
    | '/ai-followup/$customerId'
    | '/customers/$id'
    | '/projects/$id'
    | '/customers/'
    | '/api/public/card-leads/$slug'
    | '/api/public/landing-manifest/$slug'
    | '/api/public/lead-forms/$slug'
    | '/api/public/pq/$code'
    | '/api/public/q/$code'
    | '/api/public/sales-pages/$slug'
    | '/api/public/t/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customize'
    | '/login'
    | '/onboarding'
    | '/thank-you'
    | '/verify-email'
    | '/ai-followup'
    | '/ai-lead-score'
    | '/ai-sales-page'
    | '/airdrop'
    | '/analytics'
    | '/appointments'
    | '/auth-settings'
    | '/card-designer'
    | '/content-library'
    | '/dashboard'
    | '/digital-card'
    | '/dynamic-qr'
    | '/files'
    | '/landings'
    | '/lead-capture'
    | '/leads'
    | '/marketing'
    | '/members'
    | '/nfc-codes'
    | '/pipeline'
    | '/products'
    | '/projects'
    | '/prompt-library'
    | '/qr-sharing'
    | '/sale-customers'
    | '/sale-landings'
    | '/sale-projects'
    | '/settings'
    | '/team'
    | '/timeline'
    | '/wallet'
    | '/accept-invite/$token'
    | '/c/$slug'
    | '/f/$slug'
    | '/p/$slug'
    | '/share/$slug'
    | '/ai-followup/$customerId'
    | '/customers/$id'
    | '/projects/$id'
    | '/customers'
    | '/api/public/card-leads/$slug'
    | '/api/public/landing-manifest/$slug'
    | '/api/public/lead-forms/$slug'
    | '/api/public/pq/$code'
    | '/api/public/q/$code'
    | '/api/public/sales-pages/$slug'
    | '/api/public/t/$code'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/customize'
    | '/login'
    | '/onboarding'
    | '/thank-you'
    | '/verify-email'
    | '/_app/ai-followup'
    | '/_app/ai-lead-score'
    | '/_app/ai-sales-page'
    | '/_app/airdrop'
    | '/_app/analytics'
    | '/_app/appointments'
    | '/_app/auth-settings'
    | '/_app/card-designer'
    | '/_app/content-library'
    | '/_app/dashboard'
    | '/_app/digital-card'
    | '/_app/dynamic-qr'
    | '/_app/files'
    | '/_app/landings'
    | '/_app/lead-capture'
    | '/_app/leads'
    | '/_app/marketing'
    | '/_app/members'
    | '/_app/nfc-codes'
    | '/_app/pipeline'
    | '/_app/products'
    | '/_app/projects'
    | '/_app/prompt-library'
    | '/_app/qr-sharing'
    | '/_app/sale-customers'
    | '/_app/sale-landings'
    | '/_app/sale-projects'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/timeline'
    | '/_app/wallet'
    | '/accept-invite/$token'
    | '/c/$slug'
    | '/f/$slug'
    | '/p/$slug'
    | '/share/$slug'
    | '/_app/ai-followup/$customerId'
    | '/_app/customers/$id'
    | '/_app/projects/$id'
    | '/_app/customers/'
    | '/api/public/card-leads/$slug'
    | '/api/public/landing-manifest/$slug'
    | '/api/public/lead-forms/$slug'
    | '/api/public/pq/$code'
    | '/api/public/q/$code'
    | '/api/public/sales-pages/$slug'
    | '/api/public/t/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CustomizeRoute: typeof CustomizeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ThankYouRoute: typeof ThankYouRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  CSlugRoute: typeof CSlugRoute
  FSlugRoute: typeof FSlugRoute
  PSlugRoute: typeof PSlugRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiPublicCardLeadsSlugRoute: typeof ApiPublicCardLeadsSlugRoute
  ApiPublicLandingManifestSlugRoute: typeof ApiPublicLandingManifestSlugRoute
  ApiPublicLeadFormsSlugRoute: typeof ApiPublicLeadFormsSlugRoute
  ApiPublicPqCodeRoute: typeof ApiPublicPqCodeRoute
  ApiPublicQCodeRoute: typeof ApiPublicQCodeRoute
  ApiPublicSalesPagesSlugRoute: typeof ApiPublicSalesPagesSlugRoute
  ApiPublicTCodeRoute: typeof ApiPublicTCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sale-projects': {
      id: '/_app/sale-projects'
      path: '/sale-projects'
      fullPath: '/sale-projects'
      preLoaderRoute: typeof AppSaleProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sale-landings': {
      id: '/_app/sale-landings'
      path: '/sale-landings'
      fullPath: '/sale-landings'
      preLoaderRoute: typeof AppSaleLandingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sale-customers': {
      id: '/_app/sale-customers'
      path: '/sale-customers'
      fullPath: '/sale-customers'
      preLoaderRoute: typeof AppSaleCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr-sharing': {
      id: '/_app/qr-sharing'
      path: '/qr-sharing'
      fullPath: '/qr-sharing'
      preLoaderRoute: typeof AppQrSharingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompt-library': {
      id: '/_app/prompt-library'
      path: '/prompt-library'
      fullPath: '/prompt-library'
      preLoaderRoute: typeof AppPromptLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nfc-codes': {
      id: '/_app/nfc-codes'
      path: '/nfc-codes'
      fullPath: '/nfc-codes'
      preLoaderRoute: typeof AppNfcCodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead-capture': {
      id: '/_app/lead-capture'
      path: '/lead-capture'
      fullPath: '/lead-capture'
      preLoaderRoute: typeof AppLeadCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/landings': {
      id: '/_app/landings'
      path: '/landings'
      fullPath: '/landings'
      preLoaderRoute: typeof AppLandingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dynamic-qr': {
      id: '/_app/dynamic-qr'
      path: '/dynamic-qr'
      fullPath: '/dynamic-qr'
      preLoaderRoute: typeof AppDynamicQrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digital-card': {
      id: '/_app/digital-card'
      path: '/digital-card'
      fullPath: '/digital-card'
      preLoaderRoute: typeof AppDigitalCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content-library': {
      id: '/_app/content-library'
      path: '/content-library'
      fullPath: '/content-library'
      preLoaderRoute: typeof AppContentLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/card-designer': {
      id: '/_app/card-designer'
      path: '/card-designer'
      fullPath: '/card-designer'
      preLoaderRoute: typeof AppCardDesignerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth-settings': {
      id: '/_app/auth-settings'
      path: '/auth-settings'
      fullPath: '/auth-settings'
      preLoaderRoute: typeof AppAuthSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/airdrop': {
      id: '/_app/airdrop'
      path: '/airdrop'
      fullPath: '/airdrop'
      preLoaderRoute: typeof AppAirdropRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-sales-page': {
      id: '/_app/ai-sales-page'
      path: '/ai-sales-page'
      fullPath: '/ai-sales-page'
      preLoaderRoute: typeof AppAiSalesPageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-lead-score': {
      id: '/_app/ai-lead-score'
      path: '/ai-lead-score'
      fullPath: '/ai-lead-score'
      preLoaderRoute: typeof AppAiLeadScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-followup': {
      id: '/_app/ai-followup'
      path: '/ai-followup'
      fullPath: '/ai-followup'
      preLoaderRoute: typeof AppAiFollowupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-followup/$customerId': {
      id: '/_app/ai-followup/$customerId'
      path: '/$customerId'
      fullPath: '/ai-followup/$customerId'
      preLoaderRoute: typeof AppAiFollowupCustomerIdRouteImport
      parentRoute: typeof AppAiFollowupRoute
    }
    '/api/public/t/$code': {
      id: '/api/public/t/$code'
      path: '/api/public/t/$code'
      fullPath: '/api/public/t/$code'
      preLoaderRoute: typeof ApiPublicTCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sales-pages/$slug': {
      id: '/api/public/sales-pages/$slug'
      path: '/api/public/sales-pages/$slug'
      fullPath: '/api/public/sales-pages/$slug'
      preLoaderRoute: typeof ApiPublicSalesPagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/q/$code': {
      id: '/api/public/q/$code'
      path: '/api/public/q/$code'
      fullPath: '/api/public/q/$code'
      preLoaderRoute: typeof ApiPublicQCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pq/$code': {
      id: '/api/public/pq/$code'
      path: '/api/public/pq/$code'
      fullPath: '/api/public/pq/$code'
      preLoaderRoute: typeof ApiPublicPqCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-forms/$slug': {
      id: '/api/public/lead-forms/$slug'
      path: '/api/public/lead-forms/$slug'
      fullPath: '/api/public/lead-forms/$slug'
      preLoaderRoute: typeof ApiPublicLeadFormsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/landing-manifest/$slug': {
      id: '/api/public/landing-manifest/$slug'
      path: '/api/public/landing-manifest/$slug'
      fullPath: '/api/public/landing-manifest/$slug'
      preLoaderRoute: typeof ApiPublicLandingManifestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/card-leads/$slug': {
      id: '/api/public/card-leads/$slug'
      path: '/api/public/card-leads/$slug'
      fullPath: '/api/public/card-leads/$slug'
      preLoaderRoute: typeof ApiPublicCardLeadsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAiFollowupRouteChildren {
  AppAiFollowupCustomerIdRoute: typeof AppAiFollowupCustomerIdRoute
}

const AppAiFollowupRouteChildren: AppAiFollowupRouteChildren = {
  AppAiFollowupCustomerIdRoute: AppAiFollowupCustomerIdRoute,
}

const AppAiFollowupRouteWithChildren = AppAiFollowupRoute._addFileChildren(
  AppAiFollowupRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAiFollowupRoute: typeof AppAiFollowupRouteWithChildren
  AppAiLeadScoreRoute: typeof AppAiLeadScoreRoute
  AppAiSalesPageRoute: typeof AppAiSalesPageRoute
  AppAirdropRoute: typeof AppAirdropRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAuthSettingsRoute: typeof AppAuthSettingsRoute
  AppCardDesignerRoute: typeof AppCardDesignerRoute
  AppContentLibraryRoute: typeof AppContentLibraryRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDigitalCardRoute: typeof AppDigitalCardRoute
  AppDynamicQrRoute: typeof AppDynamicQrRoute
  AppFilesRoute: typeof AppFilesRoute
  AppLandingsRoute: typeof AppLandingsRoute
  AppLeadCaptureRoute: typeof AppLeadCaptureRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMembersRoute: typeof AppMembersRoute
  AppNfcCodesRoute: typeof AppNfcCodesRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppPromptLibraryRoute: typeof AppPromptLibraryRoute
  AppQrSharingRoute: typeof AppQrSharingRoute
  AppSaleCustomersRoute: typeof AppSaleCustomersRoute
  AppSaleLandingsRoute: typeof AppSaleLandingsRoute
  AppSaleProjectsRoute: typeof AppSaleProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppWalletRoute: typeof AppWalletRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiFollowupRoute: AppAiFollowupRouteWithChildren,
  AppAiLeadScoreRoute: AppAiLeadScoreRoute,
  AppAiSalesPageRoute: AppAiSalesPageRoute,
  AppAirdropRoute: AppAirdropRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAuthSettingsRoute: AppAuthSettingsRoute,
  AppCardDesignerRoute: AppCardDesignerRoute,
  AppContentLibraryRoute: AppContentLibraryRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDigitalCardRoute: AppDigitalCardRoute,
  AppDynamicQrRoute: AppDynamicQrRoute,
  AppFilesRoute: AppFilesRoute,
  AppLandingsRoute: AppLandingsRoute,
  AppLeadCaptureRoute: AppLeadCaptureRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMembersRoute: AppMembersRoute,
  AppNfcCodesRoute: AppNfcCodesRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppProductsRoute: AppProductsRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppPromptLibraryRoute: AppPromptLibraryRoute,
  AppQrSharingRoute: AppQrSharingRoute,
  AppSaleCustomersRoute: AppSaleCustomersRoute,
  AppSaleLandingsRoute: AppSaleLandingsRoute,
  AppSaleProjectsRoute: AppSaleProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppWalletRoute: AppWalletRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CustomizeRoute: CustomizeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ThankYouRoute: ThankYouRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  CSlugRoute: CSlugRoute,
  FSlugRoute: FSlugRoute,
  PSlugRoute: PSlugRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiPublicCardLeadsSlugRoute: ApiPublicCardLeadsSlugRoute,
  ApiPublicLandingManifestSlugRoute: ApiPublicLandingManifestSlugRoute,
  ApiPublicLeadFormsSlugRoute: ApiPublicLeadFormsSlugRoute,
  ApiPublicPqCodeRoute: ApiPublicPqCodeRoute,
  ApiPublicQCodeRoute: ApiPublicQCodeRoute,
  ApiPublicSalesPagesSlugRoute: ApiPublicSalesPagesSlugRoute,
  ApiPublicTCodeRoute: ApiPublicTCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
