/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppQrSharingRouteImport } from './routes/_app.qr-sharing'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppDynamicQrRouteImport } from './routes/_app.dynamic-qr'
import { Route as AppDigitalCardRouteImport } from './routes/_app.digital-card'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAiSalesPageRouteImport } from './routes/_app.ai-sales-page'
import { Route as AppAiLeadScoreRouteImport } from './routes/_app.ai-lead-score'
import { Route as AppAiFollowupRouteImport } from './routes/_app.ai-followup'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppQrSharingRoute = AppQrSharingRouteImport.update({
  id: '/qr-sharing',
  path: '/qr-sharing',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDynamicQrRoute = AppDynamicQrRouteImport.update({
  id: '/dynamic-qr',
  path: '/dynamic-qr',
  getParentRoute: () => AppRoute,
} as any)
const AppDigitalCardRoute = AppDigitalCardRouteImport.update({
  id: '/digital-card',
  path: '/digital-card',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiSalesPageRoute = AppAiSalesPageRouteImport.update({
  id: '/ai-sales-page',
  path: '/ai-sales-page',
  getParentRoute: () => AppRoute,
} as any)
const AppAiLeadScoreRoute = AppAiLeadScoreRouteImport.update({
  id: '/ai-lead-score',
  path: '/ai-lead-score',
  getParentRoute: () => AppRoute,
} as any)
const AppAiFollowupRoute = AppAiFollowupRouteImport.update({
  id: '/ai-followup',
  path: '/ai-followup',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-followup': typeof AppAiFollowupRoute
  '/ai-lead-score': typeof AppAiLeadScoreRoute
  '/ai-sales-page': typeof AppAiSalesPageRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/digital-card': typeof AppDigitalCardRoute
  '/dynamic-qr': typeof AppDynamicQrRoute
  '/leads': typeof AppLeadsRoute
  '/pipeline': typeof AppPipelineRoute
  '/qr-sharing': typeof AppQrSharingRoute
  '/team': typeof AppTeamRoute
  '/wallet': typeof AppWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-followup': typeof AppAiFollowupRoute
  '/ai-lead-score': typeof AppAiLeadScoreRoute
  '/ai-sales-page': typeof AppAiSalesPageRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/digital-card': typeof AppDigitalCardRoute
  '/dynamic-qr': typeof AppDynamicQrRoute
  '/leads': typeof AppLeadsRoute
  '/pipeline': typeof AppPipelineRoute
  '/qr-sharing': typeof AppQrSharingRoute
  '/team': typeof AppTeamRoute
  '/wallet': typeof AppWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-followup': typeof AppAiFollowupRoute
  '/_app/ai-lead-score': typeof AppAiLeadScoreRoute
  '/_app/ai-sales-page': typeof AppAiSalesPageRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/digital-card': typeof AppDigitalCardRoute
  '/_app/dynamic-qr': typeof AppDynamicQrRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/qr-sharing': typeof AppQrSharingRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/wallet': typeof AppWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-followup'
    | '/ai-lead-score'
    | '/ai-sales-page'
    | '/analytics'
    | '/dashboard'
    | '/digital-card'
    | '/dynamic-qr'
    | '/leads'
    | '/pipeline'
    | '/qr-sharing'
    | '/team'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-followup'
    | '/ai-lead-score'
    | '/ai-sales-page'
    | '/analytics'
    | '/dashboard'
    | '/digital-card'
    | '/dynamic-qr'
    | '/leads'
    | '/pipeline'
    | '/qr-sharing'
    | '/team'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-followup'
    | '/_app/ai-lead-score'
    | '/_app/ai-sales-page'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/digital-card'
    | '/_app/dynamic-qr'
    | '/_app/leads'
    | '/_app/pipeline'
    | '/_app/qr-sharing'
    | '/_app/team'
    | '/_app/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr-sharing': {
      id: '/_app/qr-sharing'
      path: '/qr-sharing'
      fullPath: '/qr-sharing'
      preLoaderRoute: typeof AppQrSharingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dynamic-qr': {
      id: '/_app/dynamic-qr'
      path: '/dynamic-qr'
      fullPath: '/dynamic-qr'
      preLoaderRoute: typeof AppDynamicQrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digital-card': {
      id: '/_app/digital-card'
      path: '/digital-card'
      fullPath: '/digital-card'
      preLoaderRoute: typeof AppDigitalCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-sales-page': {
      id: '/_app/ai-sales-page'
      path: '/ai-sales-page'
      fullPath: '/ai-sales-page'
      preLoaderRoute: typeof AppAiSalesPageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-lead-score': {
      id: '/_app/ai-lead-score'
      path: '/ai-lead-score'
      fullPath: '/ai-lead-score'
      preLoaderRoute: typeof AppAiLeadScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-followup': {
      id: '/_app/ai-followup'
      path: '/ai-followup'
      fullPath: '/ai-followup'
      preLoaderRoute: typeof AppAiFollowupRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiFollowupRoute: typeof AppAiFollowupRoute
  AppAiLeadScoreRoute: typeof AppAiLeadScoreRoute
  AppAiSalesPageRoute: typeof AppAiSalesPageRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDigitalCardRoute: typeof AppDigitalCardRoute
  AppDynamicQrRoute: typeof AppDynamicQrRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppQrSharingRoute: typeof AppQrSharingRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiFollowupRoute: AppAiFollowupRoute,
  AppAiLeadScoreRoute: AppAiLeadScoreRoute,
  AppAiSalesPageRoute: AppAiSalesPageRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDigitalCardRoute: AppDigitalCardRoute,
  AppDynamicQrRoute: AppDynamicQrRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppQrSharingRoute: AppQrSharingRoute,
  AppTeamRoute: AppTeamRoute,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
